package org.automation.enums;

/**
 *
 * Key name of all the properties mentioned in property file.
 * <br><br>
 * @author Jagrut
 * @version 1.0
 *
 */
public enum ConfigMap {

	URLFORENV,
	TESTERNAME,
	ENVIRONMENT,
	DOWNLOADWEBDRIVER,
	RUNMODE,
	REMOTEURL,
	DELETEOLDREPORTS,
	NUMBEROFDAYS,
	OVERRIDEREPORTS,
	PASSEDSCREENSHOT,
	RETRYFAILEDTESTCASES,
	USEELK,
	ELKSUITEURL,
	SENDMAILAFTEREXECUTION,
	SENDMAILUSING,
	SENDERSID,
	EMAILPASSWORD,
	RECEIVERSID
}
